<!-- content starts -->
<div>
    <ul class="breadcrumb">
        <li>
            <a href="#">Home</a>
        </li>
        <li>
            <a href="#">Forms</a>
        </li>
    </ul>
</div>

<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2><i class="glyphicon glyphicon-edit"></i> Form</h2>
            </div>
            <div class="box-content">
                <form role="form" method="post" action="/admin/role/insnew">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Email address</label>
                        <input type="email" name="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>
                        <input type="password" name="password" class="form-control" id="exampleInputPassword1" min="6" placeholder="Enter Password">
                    </div>
                    <div class="form-group">
                        <label for="nickname1">nick name</label>
                        <input name="nickname" type="text" class="form-control" id="nickname1" min="2" placeholder="Enter Nick Name">
                    </div>
                    <div class="form-group">
                        <div class="control-group">

                            <label class="control-label" for="selectError">role</label>

                            <div class="controls">
                                <select id="selectError" data-rel="chosen" name="roleid">
                                    <?php echo $option;?>
                                </select>
                            </div>
                        </div>

                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>

            </div>
        </div>
    </div>
    <!--/span-->
</div>

<!-- content ends -->