<!-- left menu starts -->
<div class="col-sm-2 col-lg-2">
    <div class="sidebar-nav">
        <div class="nav-canvas">
            <div class="nav-sm nav nav-stacked"></div>
            <ul class="nav nav-pills nav-stacked main-menu">

                <li>
                    <a class="ajax-link" href="/admin/main/main"><i class="glyphicon glyphicon-home"></i><span> Dashboard</span></a>
                </li>
                <?php
                echo LeftBuilder::menuHtml();
                ?>
                <!--<li class="accordion">
                    <a href="#"><i class="glyphicon glyphicon-chevron-right"></i><span>文章管理</span></a>
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="/admin/articles/list">列表</a></li>
                    </ul>
                </li>
                <li class="accordion">
                    <a href="#"><i class="glyphicon glyphicon-chevron-right"></i><span>角色管理</span></a>
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="/admin/role/list">列表</a></li>
                        <li><a href="/admin/role/insnew">新加</a></li>
                    </ul>
                </li>-->
            </ul>

        </div>
    </div>
</div>
<!--/span-->
<!-- left menu ends -->