<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="/statics/favicon.ico" type="image/png">
    <title>新浪</title>
    <link href="/statics/bracket/css/style.default.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="/statics/bracket/js/html5shiv.js"></script>
    <script src="/statics/bracket/js/respond.min.js"></script>
    <![endif]-->
</head>

<body class="signin">
<section>
    <div class="signinpanel">

        <div class="row">

            <div class="col-md-7">

                <div class="signin-info">
                    <div class="logopanel">
                        <h1><span>[</span> bracket <span>]</span></h1>
                    </div>
                    <!-- logopanel -->

                    <div class="mb20"></div>

                    <h5><strong>Welcome to Bracket Bootstrap 3 Template!</strong></h5>
                    <ul>
                        <li><i class="fa fa-arrow-circle-o-right mr5"></i> Fully Responsive Layout</li>
                        <li><i class="fa fa-arrow-circle-o-right mr5"></i> HTML5/CSS3 Valid</li>
                        <li><i class="fa fa-arrow-circle-o-right mr5"></i> Retina Ready</li>
                        <li><i class="fa fa-arrow-circle-o-right mr5"></i> WYSIWYG CKEditor</li>
                        <li><i class="fa fa-arrow-circle-o-right mr5"></i> and much more...</li>
                    </ul>
                    <div class="mb20"></div>
                    <strong>Not a member? <a href="signup.html">Sign Up</a></strong>
                </div>
                <!-- signin0-info -->

            </div>
            <!-- col-sm-7 -->

            <div class="col-md-5">

                <form method="post" action="/admin/index/login">
                    <h4 class="nomargin">Sign In</h4>

                    <p class="mt5 mb20">Login to access your account.</p>

                    <input type="text" class="form-control uname" placeholder="Username" name="user"/>
                    <input type="password" class="form-control pword" placeholder="Password" name="pass"/>
                    <a href="">
                        <small>Forgot Your Password?</small>
                    </a>
                    <button class="btn btn-success btn-block">Sign In</button>

                </form>
            </div>
            <!-- col-sm-5 -->

        </div>
        <!-- row -->

        <div class="signup-footer">
            <div class="pull-left">
                &copy; 2014. All Rights Reserved. Bracket Bootstrap 3 Admin Template
            </div>
            <div class="pull-right">
                Created By: <a href="http://themepixels.com/" target="_blank">ThemePixels</a>
            </div>
        </div>

    </div>
    <!-- signin -->

</section>


<!--<script src="/statics/bracket/js/jquery-1.11.1.min.js"></script>-->
<!--<script src="/statics/bracket/js/jquery-migrate-1.2.1.min.js"></script>-->
<!--<script src="/statics/bracket/js/bootstrap.min.js"></script>-->
<!--<script src="/statics/bracket/js/modernizr.min.js"></script>-->
<!--<script src="/statics/bracket/js/jquery.sparkline.min.js"></script>-->
<!--<script src="/statics/bracket/js/jquery.cookies.js"></script>-->
<!---->
<!--<script src="/statics/bracket/js/toggles.min.js"></script>-->
<!--<script src="/statics/bracket/js/retina.min.js"></script>-->
<!---->
<!--<script src="/statics/bracket/js/custom.js"></script>-->

<script src="/statics/scripts/libs/seajs/sea.js"></script>
<script src="/statics/scripts/libs/seajs/sea-config.js"></script>
<script>
    seajs.use('/statics/scripts/page/admin/login.js');
</script>


</body>
</html>
