<div class="row">
    <div class="col-sm-13">

        <div class="table-responsive">
            <table class="table table-bordered mb30">
                <thead>
                <tr>
                    <th>服务器</th>
                    <th>信息</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>系统</td>
                    <td><?php echo $os; ?></td>
                </tr>
                <tr>
                    <td>运行环境</td>
                    <td><?php echo $runEnv; ?></td>
                </tr>
                <tr>
                    <td>php版本</td>
                    <td><?php echo $phpVer; ?></td>
                </tr>
                <tr>
                    <td>php运行方式</td>
                    <td><?php echo $runPhp; ?></td>
                </tr>
                <tr>
                    <td>yaf版本</td>
                    <td><?php echo $yafVer; ?></td>
                </tr>
                <tr>
                    <td>最大上传文件体积</td>
                    <td><?php echo $maxUploadSize; ?></td>
                </tr>
                <tr>
                    <td>最长可运行时间</td>
                    <td><?php echo $maxExecutionTime; ?></td>
                </tr>
                <tr>
                    <td>本次登录的IP地址</td>
                    <td><?php echo $loginIP; ?></td>
                </tr>
                <tr>
                    <td>内存使用率</td>
                    <td><?php echo $memoryUsage; ?></td>
                </tr>
                <tr>
                    <td>磁盘使用率</td>
                    <td><?php echo $diskUsage; ?></td>
                </tr>
                <tr>
                    <td>服务器时间</td>
                    <td><?php echo $serverTime; ?></td>
                </tr>
                </tbody>
            </table>
        </div>
        <!-- table-responsive -->

    </div>
    <!-- col-sm-7 -->
</div><!-- row -->
