<!-- content starts -->
<div>
    <ul class="breadcrumb">
        <li>
            <a href="#">Home</a>
        </li>
        <li>
            <a href="#">Dashboard</a>
        </li>
    </ul>
</div>

<div class="row">

    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well">
                <h2><i class="glyphicon glyphicon-list-alt"></i> view total</h2>
            </div>
            <div class="box-content">
                <div id="sincos" class="center" style="height:300px"></div>
                <p id="hoverdata">Mouse position at (<span id="x">0</span>, <span id="y">0</span>). <span
                        id="clickdata"></span></p>
            </div>
        </div>
    </div>

</div><!--/row-->

<!-- chart libraries start -->
<script src="/statics/charisma/components/flot/excanvas.min.js"></script>
<script src="/statics/charisma/components/flot/jquery.flot.js"></script>
<script src="/statics/charisma/components/flot/jquery.flot.pie.js"></script>
<script src="/statics/charisma/components/flot/jquery.flot.stack.js"></script>
<script src="/statics/charisma/components/flot/jquery.flot.resize.js"></script>
<!-- chart libraries end -->
<script src="/statics/scripts/page/admin/initCharts.js"></script>

<!-- content ends -->