<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8"/>
    <title>404</title>
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta content="yes" name="apple-touch-fullscreen"/>
    <meta name="format-detection" content="telephone=no" />
    <meta name="author" content="mojichina" />
    <link rel="stylesheet" type="text/css" href="/statics/styles/page/404/index.css"/>
</head>
<body>
<section class="error-404">
    <div class="error-404-in">
        <div class="e404">
            <div class="img"></div>
        </div>
        <div class="ta-c"><button class="btn btn-info"  onclick="javascript:history.back();">返回上一页</button><?php echo $code;?></div>
    </div>
    <div style="display: none;"><?php echo $msg;?></div>
</section>

</body>
</html>
