<div class="panel-heading">
    <div class="panel-btns">
        <a href="" class="panel-close">×</a>
        <a href="" class="minimize">−</a>
    </div>
    <h4 class="panel-title">添加内容</h4>
</div>

<div class="panel-body panel-body-nopadding">
    <form class="form-horizontal form-bordered" method="post" action="/admin/article/postData" accept-charset="utf-8" enctype="application/x-www-form-urlencoded">
        <div class="form-group">
            <div class="col-sm-13">
                <input type="text" placeholder="title ..." class="form-control" name="title" id="title">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-13">
                <textarea id="wysiwyg" class="form-control" rows="10" style="height: 300px;" name="content"></textarea>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-13">
                <button class="btn btn-primary" id="submit">Submit</button>
            </div>
        </div>
    </form>
</div>
<!-- panel-body -->

<script>
    seajs.use('/statics/scripts/page/admin/editor.js');
</script>