<div class="panel panel-default">
    <div class="panel-heading">
        <div class="panel-btns">
            <a href="" class="panel-close">×</a>
            <a href="" class="minimize">−</a>
        </div>
        <!-- panel-btns -->
        <h3 class="panel-title">Data Tables</h3>
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <div id="table1_wrapper" class="dataTables_wrapper no-footer">
                <table class="table dataTable no-footer" id="table1" role="grid" aria-describedby="table1_info">
                    <thead>
                    <tr role="row">
                        <th class="sorting" tabindex="0" aria-controls="table1" rowspan="1" colspan="1"
                            aria-label="Rendering engine: activate to sort column ascending" style="width: 155px;">
                            Rendering engine
                        </th>
                        <th class="sorting" tabindex="0" aria-controls="table1" rowspan="1" colspan="1"
                            aria-label="Browser: activate to sort column ascending" style="width: 238px;">Browser
                        </th>
                        <th class="sorting_desc" tabindex="0" aria-controls="table1" rowspan="1" colspan="1"
                            aria-label="Platform(s): activate to sort column ascending" style="width: 229px;"
                            aria-sort="descending">Platform(s)
                        </th>
                        <th class="sorting" tabindex="0" aria-controls="table1" rowspan="1" colspan="1"
                            aria-label="Engine version: activate to sort column ascending" style="width: 125px;">Engine
                            version
                        </th>
                        <th class="sorting" tabindex="0" aria-controls="table1" rowspan="1" colspan="1"
                            aria-label="CSS grade: activate to sort column ascending" style="width: 94px;">CSS grade
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr class="gradeC odd" role="row">
                        <td class="">Misc</td>
                        <td>IE Mobile</td>
                        <td class="sorting_1">Windows Mobile 6</td>
                        <td class="center">-</td>
                        <td class="center">C</td>
                    </tr>
                    <tr class="gradeA even" role="row">
                        <td class="">Trident</td>
                        <td>Internet Explorer 7</td>
                        <td class="sorting_1">Win XP SP2+</td>
                        <td class="center">7</td>
                        <td class="center">A</td>
                    </tr>
                    <tr class="gradeA odd" role="row">
                        <td class="">Trident</td>
                        <td>AOL browser (AOL desktop)</td>
                        <td class="sorting_1">Win XP</td>
                        <td class="center">6</td>
                        <td class="center">A</td>
                    </tr>
                    <tr class="gradeA even" role="row">
                        <td class="">Gecko</td>
                        <td>Netscape Browser 8</td>
                        <td class="sorting_1">Win 98SE+</td>
                        <td class="center">1.7</td>
                        <td class="center">A</td>
                    </tr>
                    <tr class="gradeA odd" role="row">
                        <td class="">Gecko</td>
                        <td>Firefox 1.0</td>
                        <td class="sorting_1">Win 98+ / OSX.2+</td>
                        <td class="center">1.7</td>
                        <td class="center">A</td>
                    </tr>
                    <tr class="gradeA even" role="row">
                        <td class="">Gecko</td>
                        <td>Firefox 1.5</td>
                        <td class="sorting_1">Win 98+ / OSX.2+</td>
                        <td class="center">1.8</td>
                        <td class="center">A</td>
                    </tr>
                    <tr class="gradeA odd" role="row">
                        <td class="">Gecko</td>
                        <td>Firefox 2.0</td>
                        <td class="sorting_1">Win 98+ / OSX.2+</td>
                        <td class="center">1.8</td>
                        <td class="center">A</td>
                    </tr>
                    <tr class="gradeA even" role="row">
                        <td class="">Gecko</td>
                        <td>Netscape Navigator 9</td>
                        <td class="sorting_1">Win 98+ / OSX.2+</td>
                        <td class="center">1.8</td>
                        <td class="center">A</td>
                    </tr>
                    <tr class="gradeA odd" role="row">
                        <td class="">Gecko</td>
                        <td>Seamonkey 1.1</td>
                        <td class="sorting_1">Win 98+ / OSX.2+</td>
                        <td class="center">1.8</td>
                        <td class="center">A</td>
                    </tr>
                    <tr class="gradeA even" role="row">
                        <td class="">Gecko</td>
                        <td>Mozilla 1.7</td>
                        <td class="sorting_1">Win 98+ / OSX.1+</td>
                        <td class="center">1.7</td>
                        <td class="center">A</td>
                    </tr>
                    <tr class="gradeA even" role="row">
                        <td class="">Gecko</td>
                        <td>Mozilla 1.7</td>
                        <td class="sorting_1">Win 98+ / OSX.1+</td>
                        <td class="center">1.7</td>
                        <td class="center">A</td>
                    </tr>
                    <tr class="gradeA even" role="row">
                        <td class="">Gecko</td>
                        <td>Mozilla 1.7</td>
                        <td class="sorting_1">Win 98+ / OSX.1+</td>
                        <td class="center">1.7</td>
                        <td class="center">A</td>
                    </tr>
                    <tr class="gradeA even" role="row">
                        <td class="">Gecko</td>
                        <td>Mozilla 1.7</td>
                        <td class="sorting_1">Win 98+ / OSX.1+</td>
                        <td class="center">1.7</td>
                        <td class="center">A</td>
                    </tr>
                    </tbody>
                </table>

            </div>
        </div>
        <!-- table-responsive -->
        <div class="clearfix mb30"></div>

    </div>
    <!-- panel-body -->
</div>


