<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="Moweather backend">
    <meta name="author" content="hui.liu@moji.com;">
    <title>新浪微博</title>

    <link rel="shortcut icon" href="/statics//favicon.ico" type="image/png">
    <link href="/statics/bracket/css/style.default.css" rel="stylesheet">
    <link href="/statics/bracket/css/jquery.gritter.css" rel="stylesheet">
    <!--//需要table-->
    <link href="/statics/bracket/css/jquery.datatables.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="/statics/bracket/js/html5shiv.js"></script>
    <script src="/statics/bracket/js/respond.min.js"></script>
    <![endif]-->
    <script src="/statics/scripts/libs/seajs/sea.js"></script>
    <script src="/statics/scripts/libs/seajs/sea-config.js"></script>
</head>

<body>

<!-- Preloader -->
<div id="preloader">
    <div id="status"><i class="fa fa-spinner fa-spin"></i></div>
</div>

<section>

    <div class="leftpanel">

        <div class="logopanel">
            <h1><span>[</span> MoWeather <span>]</span></h1>
        </div>
        <!-- logopanel -->

        <div class="leftpanelinner">

            <!-- This is only visible to small devices -->
            <div class="visible-xs hidden-sm hidden-md hidden-lg">
                <div class="media userlogged">
                    <img alt="" src="/statics/bracket/images/photos/loggeduser.png" class="media-object">

                    <div class="media-body">
                        <h4>Admin</h4>
                        <span>"Life is so funny"</span>
                    </div>
                </div>

                <h5 class="sidebartitle actitle">Account</h5>
                <ul class="nav nav-pills nav-stacked nav-bracket mb30">
                    <li><a href="/admin/index/logout"><i class="fa fa-sign-out"></i> <span>Sign Out</span></a></li>
                </ul>
            </div>

            <?php echo LeftBuilder::menuHtml(); ?>

        </div>
        <!-- leftpanelinner -->
    </div>
    <!-- leftpanel -->


    <div class="mainpanel">

        <div class="headerbar">

            <a class="menutoggle"><i class="fa fa-bars"></i></a>

            <form class="searchform" action="index.html" method="post">
                <input type="text" class="form-control" name="keyword" placeholder="Search here..."/>
            </form>

            <div class="header-right">
                <ul class="headermenu">
                    <li>
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                <img src="/statics/bracket/images/photos/loggeduser.png" alt=""/>
                                <?php
                                    echo empty($_SESSION['user'])?
                                        '' : $_SESSION['user']['uname'];
                                ?>
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu dropdown-menu-usermenu pull-right">
                                <li><a href="/admin/index/logout"><i class="glyphicon glyphicon-log-out"></i> Log
                                        Out</a></li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>
            <!-- header-right -->

        </div>
        <!-- headerbar -->

        <div class="contentpanel">
            <?php echo $content; ?>
        </div>
        <!-- contentpanel -->

    </div>
    <!-- mainpanel -->

    <div class="rightpanel">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs nav-justified">
            <li class="active"><a href="#rp-alluser" data-toggle="tab"><i class="fa fa-users"></i></a></li>
            <li><a href="#rp-favorites" data-toggle="tab"><i class="fa fa-heart"></i></a></li>
            <li><a href="#rp-history" data-toggle="tab"><i class="fa fa-clock-o"></i></a></li>
            <li><a href="#rp-settings" data-toggle="tab"><i class="fa fa-gear"></i></a></li>
        </ul>

    </div>
    <!-- rightpanel -->

</section>


<script>
    seajs.use('/statics/scripts/page/admin/custom.js');
</script>

<!--<script src="/statics/scripts/libs/jquery/jquery-1.8.3.min.js"></script>-->
<!--<script src="/statics/bracket/js/jquery-ui-1.10.3.min.js"></script>-->
<!--<script src="/statics/bracket/js/bootstrap.min.js"></script>-->
<!--<script src="/statics/bracket/js/modernizr.min.js"></script>-->
<!--<script src="/statics/bracket/js/jquery.sparkline.min.js"></script>-->
<!--<script src="/statics/bracket/js/toggles.min.js"></script>-->
<!--<script src="/statics/bracket/js/retina.min.js"></script>-->
<!--<script src="/statics/bracket/js/jquery.cookies.js"></script>-->
<!--<script src="/statics/bracket/js/flot/jquery.flot.min.js"></script>-->
<!--<script src="/statics/bracket/js/flot/jquery.flot.resize.min.js"></script>-->
<!--<script src="/statics/bracket/js/flot/jquery.flot.spline.min.js"></script>-->
<!--<script src="/statics/bracket/js/morris.min.js"></script>-->
<!--<script src="/statics/bracket/js/raphael-2.1.0.min.js"></script>-->
<!--<script src="/statics/bracket/js/jquery.datatables.min.js"></script>-->
<!--<script src="/statics/bracket/js/custom.js"></script>-->
<!--<script src="/statics/bracket/js/dashboard.js"></script>-->

</body>
</html>
