<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>life-index CMS</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="MoJi weather life-index CMS Template">
    <meta name="author" content="hui.liu">

    <!-- The styles -->
    <link id="bs-css" href="/statics/charisma/css/bootstrap-cerulean.min.css" rel="stylesheet">

    <link href="/statics/charisma/css/charisma-app.css" rel="stylesheet">
    <link href='/statics/charisma/components/fullcalendar/dist/fullcalendar.css' rel='stylesheet'>
    <link href='/statics/charisma/components/fullcalendar/dist/fullcalendar.print.css' rel='stylesheet' media='print'>
    <link href='/statics/charisma/components/chosen/chosen.min.css' rel='stylesheet'>
    <link href='/statics/charisma/components/colorbox/example3/colorbox.css' rel='stylesheet'>
    <link href='/statics/charisma/components/responsive-tables/responsive-tables.css' rel='stylesheet'>
    <link href='/statics/charisma/components/bootstrap-tour/build/css/bootstrap-tour.min.css' rel='stylesheet'>
    <link href='/statics/charisma/css/jquery.noty.css' rel='stylesheet'>
    <link href='/statics/charisma/css/noty_theme_default.css' rel='stylesheet'>
    <link href='/statics/charisma/css/elfinder.min.css' rel='stylesheet'>
    <link href='/statics/charisma/css/elfinder.theme.css' rel='stylesheet'>
    <link href='/statics/charisma/css/jquery.iphone.toggle.css' rel='stylesheet'>
    <link href='/statics/charisma/css/uploadify.css' rel='stylesheet'>
    <link href='/statics/charisma/css/animate.min.css' rel='stylesheet'>

    <!-- jQuery -->
    <script src="/statics/charisma/components/jquery/jquery-debug.js"></script>

    <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- The fav icon -->
    <link rel="shortcut icon" href="/statics/favicon.ico">

</head>
<body>
<!-- topbar starts -->
<div class="navbar navbar-default" role="navigation">

    <div class="navbar-inner">
        <button type="button" class="navbar-toggle pull-left animated flip">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand"><span>life-index CMS</span></a>

        <!-- user dropdown starts -->
        <div class="btn-group pull-right">
            <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                <i class="glyphicon glyphicon-user"></i>
                    <span class="hidden-sm hidden-xs">
                        刘辉
                    </span>
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                <li><a href="/admin/index/logout">Logout</a></li>
            </ul>
        </div>
        <!-- user dropdown ends -->

        <!-- theme selector starts -->
        <div class="btn-group pull-right theme-container">
            <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                <i class="glyphicon glyphicon-tint"></i><span
                    class="hidden-sm hidden-xs">换皮肤</span>
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" id="themes">
                <li><a data-value="classic" href="#"><i class="whitespace"></i> Classic</a></li>
                <li><a data-value="cerulean" href="#"><i class="whitespace"></i> Cerulean</a></li>
                <li><a data-value="cyborg" href="#"><i class="whitespace"></i> Cyborg</a></li>
                <li><a data-value="simplex" href="#"><i class="whitespace"></i> Simplex</a></li>
                <li><a data-value="darkly" href="#"><i class="whitespace"></i> Darkly</a></li>
                <li><a data-value="lumen" href="#"><i class="whitespace"></i> Lumen</a></li>
                <li><a data-value="slate" href="#"><i class="whitespace"></i> Slate</a></li>
                <li><a data-value="spacelab" href="#"><i class="whitespace"></i> Spacelab</a></li>
                <li><a data-value="united" href="#"><i class="whitespace"></i> United</a></li>
            </ul>
        </div>
        <!-- theme selector ends -->

    </div>
</div>
<!-- topbar ends -->
<div class="ch-container">

    <div class="row">

        <?php $this->display('Admin/left.phtml');?>
        <div id="content" class="col-lg-10 col-sm-10">
            <?php echo $content;?>
        </div>
        <!--/#content.col-md-0-->
    </div><!--/fluid-row-->

</div>
<!--/.fluid-container-->
<!-- external javascript -->

<script src="/statics/charisma/components/bootstrap/dist/js/bootstrap.min.js"></script>

<!-- library for cookie management -->
<script src="/statics/charisma/js/jquery.cookie.js"></script>
<!-- calender plugin -->
<script src='/statics/charisma/components/moment/min/moment.min.js'></script>
<script src='/statics/charisma/components/fullcalendar/dist/fullcalendar.min.js'></script>
<!-- data table plugin -->
<script src='/statics/charisma/js/jquery.dataTables.min.js'></script>

<!-- select or dropdown enhancer -->
<script src="/statics/charisma/components/chosen/chosen.jquery.min.js"></script>
<!-- plugin for gallery image view -->
<script src="/statics/charisma/components/colorbox/jquery.colorbox-min.js"></script>
<!-- notification plugin -->
<script src="/statics/charisma/js/jquery.noty.js"></script>
<!-- library for making tables responsive -->
<script src="/statics/charisma/components/responsive-tables/responsive-tables.js"></script>
<!-- tour plugin -->
<script src="/statics/charisma/components/bootstrap-tour/build/js/bootstrap-tour.min.js"></script>
<!-- star rating plugin -->
<script src="/statics/charisma/js/jquery.raty.min.js"></script>
<!-- for iOS style toggle switch -->
<script src="/statics/charisma/js/jquery.iphone.toggle.js"></script>
<!-- autogrowing textarea plugin -->
<script src="/statics/charisma/js/jquery.autogrow-textarea.js"></script>
<!-- multiple file upload plugin -->
<script src="/statics/charisma/js/jquery.uploadify-3.1.min.js"></script>
<!-- history.js for cross-browser state change on ajax -->
<script src="/statics/charisma/js/jquery.history.js"></script>
<!-- application script for Charisma demo -->
<script src="/statics/scripts/page/admin/main.js"></script>
<script src="/statics/scripts/libs/kindeditor/kindeditor.js"></script>
<script src="/statics/charisma/js/charisma.js"></script>
</body>
</html>